### ISSUE TITLE
All styles are loaded?

### ISSUE THREAD

**Issue by Werbschaft** [rasteiner/k3-awesome-picker#10]
When using the below setup, all icon styles are loaded. I thought only these two were loaded? It's cause of the really heavy load weight of all icons in all variations.

```
'rasteiner.awesome-picker' => [
  'css-url' => function() {
    return url('assets/css/icons.css');
  },
  'meta-source' => 'assets/css/icons.yml',
  'default‑styles' => ["brands", "light"],
  'loaded‑styles' => ["brands", "light"]
],
```

With this setup I get this result:

<img width="375" alt="Bildschirmfoto 2020-10-19 um 11 48 35" src="https://user-images.githubusercontent.com/2178466/96429800-a5bfa680-1201-11eb-915c-b9086e088157.png">

Also is there a limit for the icons? My list goes only until "c" and then stops

<img width="324" alt="Bildschirmfoto 2020-10-19 um 11 54 16" src="https://user-images.githubusercontent.com/2178466/96430014-e61f2480-1201-11eb-9d78-62c098d9ffa6.png">

Sorry for opening so many issues

**Comment by rasteiner** [comment]
the 'loaded‑styles' option should work (just tested it with your files).
Have you refreshed the panel after changing the option? (the meta data is cached and updates only on refresh)

the other problem (rendering only until "c") seems to be a failure of the browser to layout so many grid rows. (notice all those items that overlap). 
Maybe related: https://bugs.chromium.org/p/chromium/issues/detail?id=688640

I'm not sure how to handle this, if it would be a simple list (1 item per row), I could use those components that dynamically reuse elements (https://github.com/tangbc/vue-virtual-scroll-list), but having a grid (which I'd like to keep) makes this much more complicated...

**Comment by Werbschaft** [comment]
Yes I have cleared Browser Cache and tested also in a private window. Where are they cached? I have cleared browser, local storage and a few others.

For the overlapping, you're totally right, I've set it to display blocks and it works. So maybe it will be fixed in future. I do a little override with the good old float left 👍

**Comment by rasteiner** [comment]
"cached" as in "saved in a javascript variable" (that simply stays there when navigating the panel, but disappears when reloading the window). 

But now I got it. It's a problem with my readme.md file. Try replacing the `-` character in the option names with your own `-` character (**don't** copy them from the documentation). 
I'll need to fix this, but the dashes in the readme are no normal dashes, they are "[non breaking hyphens](https://en.wikipedia.org/wiki/Wikipedia:Non-breaking_hyphen)" (otherwise the table in the readme would break the option names on 2 rows which wasn't nice to look at. 
I didn't think abut people copy pasting them.

**Comment by Werbschaft** [comment]
Dammmn, yes you're right, have checked the config.php and I have seen the difference! Yes I have copied it from there ... now it works 😃
